#!/bin/bash

CURRENT_BRANCH=$(git branch 2> /dev/null | grep \* | cut -d ' ' -f2)
BRANCH="${1:-$CURRENT_BRANCH}"
MASTER="${2:-main}"

if [ -z $BRANCH ]; then
    echo '$BRANCH not set'
    exit 1
elif [ $BRANCH == $MASTER ]; then
    echo "Not allowed to delete $MASTER"
    exit 1
else
    echo "Deleting branch $BRANCH"
fi

read -p "Do you wish to delete branch $BRANCH? " yn
if [ $yn != "y" ]; then
    exit 0
fi

if [ $BRANCH == $CURRENT_BRANCH ]; then
    echo "Switching to $MASTER branch in order to delete $BRANCH"
    git checkout $MASTER
fi

echo "Deleting remote branch $BRANCH"
git push origin --delete $BRANCH

echo "Deleting local branch $BRANCH"
git branch -D $BRANCH

