#!/bin/bash -ex

# Update my forked repo from its upstream repo

# Stash current local changes
git stash

# Pull in any changes made on my fork
git fetch origin main
git pull origin main

# Pull in any changes from upstream
git fetch upstream --tags
git pull upstream main

# Push the upstream changes up to my fork
git push origin main --tags

# Re-apply my local stashed changes
git stash apply
